name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: junit test
      id: junit-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: junit test
        setup-command: ''
        command: mvn test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JUNIT-TEST_RESULTS: "${{steps.junit-test.outputs.result}}"
      with:
        runners: junit-test
